language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
#script:
#  - pytest
# Install the codecov pip dependency
install:
  - pip install codecov

# Run the unit test
script:
  - coverage run forwardAD_tests.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
